// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rent.Data;

#nullable disable

namespace Rent.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220616001120_four")]
    partial class four
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Rent.Entites.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "motor"
                        },
                        new
                        {
                            Id = 2,
                            Name = "motor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "motor"
                        },
                        new
                        {
                            Id = 4,
                            Name = "motor"
                        },
                        new
                        {
                            Id = 5,
                            Name = "motor"
                        },
                        new
                        {
                            Id = 6,
                            Name = "motor"
                        },
                        new
                        {
                            Id = 7,
                            Name = "motor"
                        });
                });

            modelBuilder.Entity("Rent.Entites.Models.CategorySparepart", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SparepartId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "SparepartId");

                    b.HasIndex("SparepartId");

                    b.ToTable("CategorySpareparts");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            SparepartId = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            SparepartId = 2
                        },
                        new
                        {
                            CategoryId = 3,
                            SparepartId = 3
                        },
                        new
                        {
                            CategoryId = 4,
                            SparepartId = 4
                        },
                        new
                        {
                            CategoryId = 5,
                            SparepartId = 5
                        });
                });

            modelBuilder.Entity("Rent.Entites.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "ürün 1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "ürün 1"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "ürün 1"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "ürün 1"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "ürün 1"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "ürün 1"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Name = "ürün 1"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Name = "ürün 1"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Name = "ürün 1"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Name = "ürün 1"
                        });
                });

            modelBuilder.Entity("Rent.Entites.Models.Sparepart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Spareparts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "arabalar"
                        },
                        new
                        {
                            Id = 2,
                            Name = "arabalar"
                        },
                        new
                        {
                            Id = 3,
                            Name = "arabalar"
                        },
                        new
                        {
                            Id = 4,
                            Name = "arabalar"
                        },
                        new
                        {
                            Id = 5,
                            Name = "arabalar"
                        });
                });

            modelBuilder.Entity("Rent.Entites.Models.CategorySparepart", b =>
                {
                    b.HasOne("Rent.Entites.Models.Category", "Category")
                        .WithMany("CategorySpareparts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rent.Entites.Models.Sparepart", "Sparepart")
                        .WithMany("CategorySpareparts")
                        .HasForeignKey("SparepartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Sparepart");
                });

            modelBuilder.Entity("Rent.Entites.Models.Product", b =>
                {
                    b.HasOne("Rent.Entites.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Rent.Entites.Models.Category", b =>
                {
                    b.Navigation("CategorySpareparts");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Rent.Entites.Models.Sparepart", b =>
                {
                    b.Navigation("CategorySpareparts");
                });
#pragma warning restore 612, 618
        }
    }
}
